# Generated by Django 3.2 on 2020-11-01 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20, unique=True, verbose_name='email')),
                ('clave', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Campaña',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Fecha_Creada', models.DateTimeField(verbose_name='date published')),
                ('Fecha_Inicio', models.DateTimeField(auto_now_add=True)),
                ('Fecha_Final', models.DateTimeField(auto_now_add=True)),
                ('dias_duracion', models.IntegerField()),
                ('operador_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Campaña.operador')),
            ],
        ),
    ]
