# Generated by Django 3.2 on 2020-11-02 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('cc', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.CharField(max_length=20)),
                ('celular', models.IntegerField()),
                ('email', models.EmailField(max_length=20, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='estado_campaña',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultadosxCampaña',
            fields=[
                ('contacto_cc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='Campaña.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='contactosxcampa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campaña.campaña')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Campaña.contacto')),
            ],
        ),
    ]
