# Generated by Django 3.2 on 2020-11-02 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0002_contacto_contactosxcampa_estado_campaña_resultadosxcampaña'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultadosxCampaña',
        ),
    ]
