# Generated by Django 3.2 on 2020-11-07 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0003_delete_resultadosxcampaña'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Fecha_Creada', models.DateTimeField(verbose_name='date published')),
                ('Fecha_Inicio', models.DateTimeField(auto_now_add=True)),
                ('Fecha_Final', models.DateTimeField(auto_now_add=True)),
                ('dias_duracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_asunt', models.CharField(max_length=30)),
                ('email_cuerpo', models.CharField(max_length=30)),
                ('sms_mensaje', models.CharField(max_length=20)),
                ('llamada_aud', models.FileField(upload_to='audios/')),
            ],
        ),
        migrations.CreateModel(
            name='mediosxcampania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensidad', models.IntegerField()),
                ('hora1', models.TimeField()),
                ('hora2', models.TimeField()),
                ('hora3', models.TimeField()),
                ('campania_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Campaña.campania')),
                ('medio_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Campaña.medio')),
            ],
        ),
        migrations.CreateModel(
            name='resultadosxcampania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='resultadosxmedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_medio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='contactosxcampa',
            name='campani',
        ),
        migrations.AlterField(
            model_name='contactosxcampa',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Campaña.contacto'),
        ),
        migrations.RenameModel(
            old_name='estado_campaña',
            new_name='estado_campania',
        ),
        migrations.DeleteModel(
            name='Campaña',
        ),
        migrations.AddField(
            model_name='resultadosxmedio',
            name='TipoMedio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Campaña.tipo_medio'),
        ),
        migrations.AddField(
            model_name='resultadosxmedio',
            name='tipo_resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Campaña.tipo_resultado'),
        ),
        migrations.AddField(
            model_name='resultadosxcampania',
            name='Tipo_resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Campaña.tipo_resultado'),
        ),
        migrations.AddField(
            model_name='resultadosxcampania',
            name='campania_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Campaña.campania'),
        ),
        migrations.AddField(
            model_name='resultadosxcampania',
            name='contacto_cc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Campaña.contacto'),
        ),
        migrations.AddField(
            model_name='resultadosxcampania',
            name='medio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Campaña.medio'),
        ),
        migrations.AddField(
            model_name='medio',
            name='tipo_medio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Campaña.tipo_medio'),
        ),
        migrations.AddField(
            model_name='campania',
            name='estado_campaña',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Campaña.estado_campania'),
        ),
        migrations.AddField(
            model_name='campania',
            name='operador_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Campaña.operador'),
        ),
        migrations.AddField(
            model_name='contactosxcampa',
            name='campania',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Campaña.campania'),
        ),
    ]
