# Generated by Django 3.2 on 2020-11-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0004_auto_20201107_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_campania',
            name='descripcion',
            field=models.CharField(max_length=10),
        ),
    ]
