# Generated by Django 3.2 on 2020-11-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0006_auto_20201107_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campania',
            name='Fecha_Creada',
            field=models.DateTimeField(verbose_name='Fecha creada'),
        ),
    ]
