# Generated by Django 3.2 on 2020-11-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0007_alter_campania_fecha_creada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campania',
            name='Fecha_Creada',
            field=models.DateTimeField(verbose_name='2006-10-25 14:30'),
        ),
    ]
