# Generated by Django 3.2 on 2020-11-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0011_auto_20201109_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_campania',
            name='descripcion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tipo_resultado',
            name='descripcion',
            field=models.IntegerField(),
        ),
    ]
