# Generated by Django 3.2 on 2020-11-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0012_auto_20201109_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado_campania',
            name='id',
        ),
        migrations.AlterField(
            model_name='estado_campania',
            name='descripcion',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
