# Generated by Django 3.2 on 2020-11-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0013_auto_20201122_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactosxcampa',
            name='nombreContactos',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
