# Generated by Django 3.2 on 2020-11-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0014_contactosxcampa_nombrecontactos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='contacto',
            name='fechaNacimiento',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='contacto',
            name='fijo',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='celular',
            field=models.IntegerField(default=None),
        ),
    ]
