# Generated by Django 3.2 on 2020-11-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0015_auto_20201125_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campania',
            name='Fecha_Creada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='campania',
            name='Fecha_Final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='campania',
            name='Fecha_Inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fechaNacimiento',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='resultadosxcampania',
            name='fecha',
            field=models.DateField(),
        ),
    ]
