# Generated by Django 3.2 on 2020-11-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0016_auto_20201125_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campania',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
    ]
