# Generated by Django 3.2 on 2020-11-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0017_alter_campania_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='celular',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
