# Generated by Django 3.2 on 2020-12-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0019_alter_contacto_fijo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medio',
            name='email_asunt',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medio',
            name='email_cuerpo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medio',
            name='llamada_aud',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='medio',
            name='sms_mensaje',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
