# Generated by Django 3.2 on 2020-12-22 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0020_auto_20201204_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='fechaNacimiento',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='cc',
            new_name='identidad',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='fijo',
            new_name='telefono',
        ),
    ]
