# Generated by Django 3.2 on 2020-12-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0022_auto_20201222_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='celular',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
