# Generated by Django 3.2 on 2020-12-22 22:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0024_alter_contacto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='campania',
            name='taksIds',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), null=True, size=None),
        ),
    ]
