# Generated by Django 3.2 on 2020-12-22 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0025_campania_taksids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campania',
            old_name='taksIds',
            new_name='tasksIds',
        ),
    ]
