# Generated by Django 3.2 on 2020-12-23 00:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0026_rename_taksids_campania_tasksids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campania',
            name='tasksIds',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=None, null=True, size=None),
        ),
    ]
