# Generated by Django 3.2 on 2020-12-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0027_alter_campania_tasksids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediosxcampania',
            name='hora1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediosxcampania',
            name='hora2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediosxcampania',
            name='hora3',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
