# Generated by Django 3.2 on 2020-12-23 05:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0028_auto_20201222_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campania',
            name='tasksIds',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), blank=True, default=None, null=True, size=None),
        ),
    ]
