# Generated by Django 3.2 on 2020-12-23 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0030_auto_20201223_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campania',
            old_name='estado_campaña',
            new_name='estado',
        ),
    ]
