# Generated by Django 3.2 on 2020-12-27 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0031_rename_estado_campaña_campania_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadosxcampania',
            name='Tipo_resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Campaña.tipo_resultado'),
        ),
    ]
