# Generated by Django 3.2 on 2020-12-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0032_alter_resultadosxcampania_tipo_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medio',
            name='sms_mensaje',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_resultado',
            name='descripcion',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
