# Generated by Django 3.2 on 2020-12-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0033_auto_20201227_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='identidad',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
