# Generated by Django 3.2 on 2021-06-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaña', '0034_alter_contacto_identidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medio',
            name='email_cuerpo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
