# Generated by Django 5.2.11 on 2026-02-11 05:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('Fecha_Creada', models.DateField(auto_now_add=True)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('identidad', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(default=None)),
                ('celular', models.CharField(default=None, max_length=10)),
                ('telefono', models.CharField(default=None, max_length=15)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='estado_campania',
            fields=[
                ('descripcion', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('clave', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_medio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('clave', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='contactosxcampa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreContactos', models.CharField(max_length=25, null=True)),
                ('campania', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campania')),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='campaigns.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='EmailMedio',
            fields=[
                ('medio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.medio')),
                ('asunto', models.CharField(blank=True, max_length=100, null=True)),
                ('remitente', models.EmailField(blank=True, max_length=254, null=True)),
                ('cuerpo', models.TextField(blank=True, null=True)),
            ],
            bases=('campaigns.medio',),
        ),
        migrations.CreateModel(
            name='SMSMedio',
            fields=[
                ('medio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.medio')),
                ('mensaje', models.TextField(blank=True, null=True)),
            ],
            bases=('campaigns.medio',),
        ),
        migrations.CreateModel(
            name='VoiceMedio',
            fields=[
                ('medio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.medio')),
                ('mensaje_texto', models.TextField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audios/')),
            ],
            bases=('campaigns.medio',),
        ),
        migrations.CreateModel(
            name='WhatsAppMedio',
            fields=[
                ('medio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.medio')),
                ('mensaje', models.TextField(blank=True, null=True)),
            ],
            bases=('campaigns.medio',),
        ),
        migrations.CreateModel(
            name='CampaignTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodic_task_id', models.IntegerField()),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='campaigns.campania')),
                ('medio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.medio')),
            ],
        ),
        migrations.AddField(
            model_name='campania',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.estado_campania'),
        ),
        migrations.CreateModel(
            name='mediosxcampania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensidad', models.IntegerField()),
                ('hora1', models.TimeField(blank=True, null=True)),
                ('hora2', models.TimeField(blank=True, null=True)),
                ('hora3', models.TimeField(blank=True, null=True)),
                ('campania_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.campania')),
                ('medio_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.medio')),
            ],
        ),
        migrations.AddField(
            model_name='campania',
            name='operador_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.operador'),
        ),
        migrations.AddField(
            model_name='medio',
            name='tipo_medio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.tipo_medio'),
        ),
        migrations.CreateModel(
            name='resultadosxcampania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('campania_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.campania')),
                ('contacto_cc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.contacto')),
                ('medio_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.medio')),
                ('Tipo_resultado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='campaigns.tipo_resultado')),
            ],
        ),
    ]
